#!/bin/bash

#$ -pe smp 32
#$ -q UI
#$ -m bea
#$ -M james-kent@uiowa.edu
#$ -o /Users/jdkent/Projects/betaSeriesSimulations/
#$ -e /Users/jdkent/Projects/betaSeriesSimulations/

conda activate bsim

sims_beta -w /nfsscratch/Users/jdkent/work_smol --nthreads 32 --n-simulations 100 \
          /Users/jdkent/Projects/betaSeriesSimulations/ smol_simulation32.tsv \
          /Users/jdkent/Projects/betaSeriesSimulations/data/example_config.json
