version: 2
jobs:

  build:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/src/betaSim
    steps:
      - run:
          name:  Install pigz
          command: |
            sudo apt update && sudo apt -y install pigz
      - run: 
          name: Install git-lfs
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs
            git lfs install

      - restore_cache:
          keys:
            - docker-v1-{{ .Branch }}-{{ .Revision }}
            - docker-v1-{{ .Branch }}-
            - docker-v1-master-
            - docker-v1-
          paths:
            - /tmp/cache/docker.tar.gz
      - checkout
      - run:
          name: pull large files
          command: |
            git lfs pull
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
              docker images
            fi
      - run:
          name: Build Docker image
          no_output_timeout: 60m
          command: |
            docker build \
              --cache-from=jdkent/beta_sim:dev \
              -t jdkent/beta_sim:dev \
              --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
              --build-arg VCS_REF=$(git rev-parse --short HEAD) .
      - run:
          name: pytest Docker image
          no_output_timeout: 120m
          command: |
            docker run --entrypoint /neurodocker/startup.sh jdkent/beta_sim:dev \
            bash -c ". activate betaseries_simulation && pytest /home/coder/project"
      - run:
          name: Docker save
          no_output_timeout: 30m
          command: |
            mkdir -p /tmp/cache
            docker save jdkent/beta_sim:dev | pigz -3 > /tmp/cache/docker.tar.gz
      - save_cache:
          key: docker-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - /tmp/cache/docker.tar.gz

